# Generated by Django 4.0.2 on 2022-03-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
