# Generated by Django 4.0.2 on 2022-03-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='price',
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_product_id',
            field=models.CharField(default='prod_LNbJHMjBBddmyy', max_length=100),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
            ],
        ),
    ]
