# Generated by Django 4.0.2 on 2022-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_digital_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fufilled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
