# Generated by Django 4.0.2 on 2022-03-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_calories_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formmetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_tracker', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
