# Generated by Django 4.0.2 on 2022-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_calories_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='notes',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
    ]
