# Generated by Django 4.0.3 on 2022-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_form_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitems',
            name='form',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
