# Generated by Django 4.0.2 on 2022-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_ID', models.IntegerField(blank=True, default=0, null=True)),
                ('order_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_ID', models.IntegerField(blank=True, default=0, null=True)),
                ('order_Date', models.DateTimeField(null=True)),
            ],
        ),
    ]
